# default false
release_mode = false
# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"
# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"
# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Echo Web"
#debug or release
mode = "debug"

[server]
graceful = true
addr = ":10002"
writeTimeout = "5s"
readTimeout = "5s"
maxHeaderBytes = 100000000000000
domain_api = "saas.YOUR_DOMAIN.com"
domain_web = "saas.YOUR_DOMAIN.com"
domain_socket = "echo.socket.localhost.com"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[tmpl]
# PONGO2,TEMPLATE(TEMPLATE Default)
type = "PONGO2"
# BINDATA,FILE(FILE Default)
data = "BINDATA"
# PONGO2(template/pongo2),TEMPLATE(template)
dir = "template/pongo2"
#dir = "template"
# .html,.tpl
suffix = ".html"

[image]
    space = "shopadmin"
    domain = "https://oss.yitum.com/"
    path = "/home/www/server/image/shopadmin"

[callerGinSession]
    name = "mysession"
    size = 10
    network = "tcp"
    addr = "127.0.0.1:6379"
    pwd = ""
    keypairs = "secret"

[callerRedigo.default]
    addr = "127.0.0.1:6379"

[callerGorm.oauth]
    debug = true
    level = "panic"
    network = "tcp"
    dialect = "mysql"
    addr = "127.0.0.1:3306"
    username = "root"
    password = "root"
    db = "shop"
    charset = "utf8"
    parseTime = "True"
    loc = "Local"
    timeout = "1s"
    readTimeout = "1s"
    writeTimeout = "1s"
    maxOpenConns = 30
    maxIdleConns = 10
    connMaxLifetime = "300s"

[callerZap.system]
    level = "debug"
    path = "./system.log"

